//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epargne : Compte
    {
        public string dateDbBlockage { get; set; }
        public string dateFinBlockage { get; set; }
        public int taux { get; set; }
    }
}
